/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package subastasis;
import VENTANAS.*;
/**
 *
 * @author Tserng
 */
public class MENU extends javax.swing.JFrame {

    /**
     * Creates new form MENU
     */
    public MENU() {
        initComponents();
       this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuClientes = new javax.swing.JMenu();
        jMenuItemRegistrar = new javax.swing.JMenuItem();
        jMenuSubasta = new javax.swing.JMenu();
        jMenuRecibo = new javax.swing.JMenu();
        jMenuFacturas = new javax.swing.JMenu();
        jMenuCheques = new javax.swing.JMenu();
        jMenuTraslados = new javax.swing.JMenu();
        jMenuReportes = new javax.swing.JMenu();
        jMenuBanco = new javax.swing.JMenu();
        jMenuAdministracion = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SUBASTA GANADERA VERAGUENSE S,A.");
        setFont(new java.awt.Font("Agency FB", 1, 12)); // NOI18N
        setName("menu"); // NOI18N

        jDesktopPane1.setBackground(new java.awt.Color(102, 153, 255));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1042, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 497, Short.MAX_VALUE)
        );

        jMenuClientes.setText("CLIENTES");

        jMenuItemRegistrar.setText("REGISTRAR");
        jMenuItemRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistrarActionPerformed(evt);
            }
        });
        jMenuClientes.add(jMenuItemRegistrar);

        jMenuBar1.add(jMenuClientes);

        jMenuSubasta.setText("SUBASTA");
        jMenuSubasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSubastaActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuSubasta);

        jMenuRecibo.setText("RECIBO");
        jMenuBar1.add(jMenuRecibo);

        jMenuFacturas.setText("FACTURAS");
        jMenuBar1.add(jMenuFacturas);

        jMenuCheques.setText("CHEQUES");
        jMenuBar1.add(jMenuCheques);

        jMenuTraslados.setText("TRASLADOS");
        jMenuBar1.add(jMenuTraslados);

        jMenuReportes.setText("REPORTES");
        jMenuBar1.add(jMenuReportes);

        jMenuBanco.setText("BANCO");
        jMenuBar1.add(jMenuBanco);

        jMenuAdministracion.setText("ADMINISTRACION");
        jMenuBar1.add(jMenuAdministracion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistrarActionPerformed
        // TODO add your handling code here:
        CLIENTES cliente = new CLIENTES();
         cliente.setVisible(true);
        this.jDesktopPane1.add(cliente);
    }//GEN-LAST:event_jMenuItemRegistrarActionPerformed

    private void jMenuSubastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSubastaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuSubastaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MENU().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenuAdministracion;
    private javax.swing.JMenu jMenuBanco;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCheques;
    private javax.swing.JMenu jMenuClientes;
    private javax.swing.JMenu jMenuFacturas;
    public static javax.swing.JMenuItem jMenuItemRegistrar;
    private javax.swing.JMenu jMenuRecibo;
    private javax.swing.JMenu jMenuReportes;
    private javax.swing.JMenu jMenuSubasta;
    private javax.swing.JMenu jMenuTraslados;
    // End of variables declaration//GEN-END:variables
}
